# Generated by Django 3.2 on 2021-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('Surname', models.CharField(max_length=30, unique=True)),
                ('Linkedin', models.URLField()),
            ],
        ),
    ]
